<?php
// $Id$
/**
 * @file
 * Main module file for the Baidu Share Embed Module
 */

/**
 * Implements hook_perm().
 * Permissions for Baidu Share button
 */
function baidu_share_permission() {
  return array(
    'administer Baidu Share button' => array(
      'title' => t('Administer Baidu Share button'),
    ),
    'view Baidu Share button' => array(
      'title' => t('View Baidu Share button'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function baidu_share_init() {
  $arg = arg();
  if ($arg == 'admin/config/services/baidu_share') {
    //drupal_add_css(drupal_get_path('module', 'baidu_share').'/baidu_share.css');
  }
}

/**
 * Implements hook_menu().
 */
function baidu_share_menu() {
  $items['admin/config/services/baidu_share'] = array(
    'title'            => 'Baidu Share Button',
    'description'      => 'Configure Baidu Share Button settings',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer Baidu Share button'),
    'file'             => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/services/baidu_share/page'] = array(
    'title'            => 'Baidu Share Button page',
    'description'      => 'Configure Baidu Share Button settings for pages',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('baidu_share_page_admin_settings'),
    'access arguments' => array('administer Baidu Share button'),
    'file'             => 'baidu_share.admin.inc',
  );
  $items['admin/config/services/baidu_share/block'] = array(
    'title'            => 'Baidu Share Button block',
    'description'      => 'Configure Baidu Share Button settings for block',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('baidu_share_block_admin_settings'),
    'access arguments' => array('administer Baidu Share button'),
    'file'             => 'baidu_share.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function baidu_share_theme() {
  return array(
    'baidu_share_button' => array(
      'arguments' => array(
        'node' => NULL,
        'url' => NULL,
        'css' => '',
        'size' => '1',
        'iconstyle' => '0',
        'count' => 1,
        'syntax' => 'baidu_sharescript',
      ),
    ),
    'baidu_share_button_block' => array(
      'arguments' => array(
        'node' => NULL,
        'url' => NULL,
        'css' => '',
        'size' => '1',
        'iconstyle' => '0',
        //'baidu_share_type' => '0',
        'count' => 1,
        'syntax' => 'baidu_sharescript',
      ),
      'variables' => array('values' => NULL,),
      'template'  => 'baidu-share-html',
    ),
  );
}

/*function theme_baidu_share_html($variables) {

  return theme('baidu_share_html',$variables);
  dpm($variables);
  //return 'Hi';
  $node = $variables['node'];
  $build = node_view($node);
  $output = drupal_render($build);
  return $output;
}*/

/**
 * Implements template_preprocess().
 *
 * We prepare variables for use inside the baidu-share-html.tpl.php
 * template file.
 *
 * @see baidu-share-html.tpl.php
 */
function template_preprocess_baidu_share_button_block(&$variables) {
  $variables['imageShare'] = ',"image":{"viewList":["qzone","tsina","tqq","renren","weixin"],"viewText":"分享到：","viewSize":"16"}';
  $variables['selectShare'] = ',"selectShare":{"bdContainerClass":null,"bdSelectMiniList":["qzone","tsina","tqq","renren","weixin"]}';
  $requirements = $variables['baidu_share_type'];
  dpm($variables);
  if (in_array('2',$requirements)) {
    $variables['imageShare']  = $variables['imageShare'];
  }else {
    $variables['imageShare'] = '';
  }

  if (in_array('3',$requirements)){
    $variables['selectShare'] = $variables['selectShare'];
  } else {
    $variables['selectShare'] = '';
  }
  //dpm($variables);
}

/**
 * Returns HTML for the Baidu Share button.
 *
 * @param $variables
 *   An associative array containing:
 *   - object: (optional) The node object. (Only will be use its nid)
 *   - size:  (optional) A string 'small', 'medium', 'standard', 'tall'
 *   - count: (optional) A integer 0 or 1 (0 default will not print aggregated counting
 *   - css: (optional) A string with inline CSS rules for the wrapper.
 *   - iconstyle: (optional) An integer 0 or 3
 *
 * @ingroup themeable
 */
/*function theme_baidu_share_button($variables) {
  $appkey = variable_get('baidu_share_appkey', '');
  $syntax = $variables['syntax'];
  $count = $variables['count'];
  $size = $variables['size'];
  $iconstyle = $variables['iconstyle'];
  //$baidu_share_btn = $iconstyle + $size;

  list($count,$button) = _baidu_share_get_options ($iconstyle, $count, $size);
  $button = _create_baidu_share_html($button,$count,$appkey,$iconstyle);

  // Wrap it and serve it
  if ($variables['css'] !== 'nowrapper') {
    $css =   empty($variables['css'])   ? '' : 'style="' .  check_plain($variables['css']) . '"';
    $button = '<div class="baidu-share-wrapper" '. $css . ' >' . $button . '</div>';
  }
  return $button;
}
*/

/**
 * Returns HTML for the Baidu Share button.
 *
 * @param $variables
 *   An associative array containing:
 *   - object: (optional) The node object. (Only will be use its nid)
 *   - size_block:  (optional) A string 'small', 'medium', 'standard', 'tall'
 *   - count_block: (optional) A integer 0 or 1 (0 default will not print aggregated counting
 *   - css_block: (optional) A string with inline CSS rules for the wrapper.
 *   - baidu_share_button-size: (optional) An integer 0 or 3
 *
 */
function theme_baidu_share_button_block($variables) {
  $appkey = variable_get('baidu_share_appkey', '');
//	$syntax = $variables['syntax'];
  $count = $variables['count_block'];
  $size = $variables['size_block'];
  $iconstyle = $variables['baidu_share_button-size'];
  $requirements = $variables['baidu_share_type'];
  $baidu_share_btn = $iconstyle + $size;

  list($count,$button,$iconstyle,$requirements) = _baidu_share_get_options ($requirements, $iconstyle, $count, $size);
  $button = _create_baidu_share_html($button,$count,$appkey,$iconstyle,$requirements);

  // Wrap it and serve it
  if ($variables['css_block'] !== 'nowrapper') {
    $css =   empty($variables['css_block'])   ? '' : 'style="' .  check_plain($variables['css_block']) . '"';
    $button = '<div class="baidu-share-wrapper" '. $css . ' >' . $button . '</div>';
  }
  return $button;
}

/**
 * Implements hook_block_info().
 *
 */
function baidu_share_block_info($op = 'list', $delta = 0, $edit = array()) {
  $blocks['baidu_share'] = array(
    'info' => t('Baidu Share button'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 */
function baidu_share_block_view($delta = '') {
  $block = array();
  if($delta == 'baidu_share'){
    $block['content'] = _generate__baidu_share_block_button();
  }
  return $block;
}

function _generate__baidu_share_block_button(){
  $default = array(
    'count_block' => 0,
    'size_block' => '1',  // standard
    'css_block' => 'margin: 0 1em 1em 1em;height:50px',
    'baidu_share_button-size' => '1',
   // 'baidu_share_type' => array('1','2','3'),
    'syntax' => 'baidu_sharescript',

  );

  //dpm(variable_get('baidu_share_type', array()));
  //$button_settings = array_merge($default, variable_get('baidu_share_type', array()));
  $button_settings = array_merge($default, array('baidu_share_type'=>variable_get('baidu_share_type', array())));
  return theme('baidu_share_button_block', $button_settings);
}



function _baidu_share_get_options ($requirements, $iconstyle, $count, $size) {


  if($count == 1){
    $count = '<a class="baidu_share_counter_style"></a>';
  } else {
    $count='';
  }

  //tiny icon
  if ($size == 4) {
    $b = '';
  }
  //small icon
  else if ($size == 3) {
    $b = '';
  }
  //medium icon
  else if ($size == 2) {
    $b = '';
  }
  //large icon && default
  else {
    $b = '';
  }

  return array($count,$b,$iconstyle,$requirements);
}


function _create_baidu_share_html($button,$count,$appkey,$iconstyle)
{
  //standard
  if($iconstyle=='0'){
    $iconstyle='_mini';
  }
  // mini
  else if ($iconstyle=='1'){
    $iconstyle='';
  }

  $output = '';
  return $output;
}

/**
 * @} End of "Baidu Share button Module".
 */
